// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"time"
)

type Favorite struct {
	UserID  int64 `json:"user_id"`
	TweetID int64 `json:"tweet_id"`
}

type Follower struct {
	UserID     int64     `json:"user_id"`
	FollowerID int64     `json:"follower_id"`
	CreatedAt  time.Time `json:"created_at"`
}

type Reply struct {
	TweetID int64 `json:"tweet_id"`
	ReplyID int64 `json:"reply_id"`
}

type Retweet struct {
	TweetID   int64 `json:"tweet_id"`
	RetweetID int64 `json:"retweet_id"`
}

type Tweet struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"user_id"`
	Post      string    `json:"post"`
	Favorites int32     `json:"favorites"`
	Replies   int32     `json:"replies"`
	Retweets  int32     `json:"retweets"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type User struct {
	ID                int64     `json:"id"`
	Username          string    `json:"username"`
	Email             string    `json:"email"`
	HashedPassword    string    `json:"hashed_password"`
	ProfilePictureUrl string    `json:"profile_picture_url"`
	HeaderPictureUrl  string    `json:"header_picture_url"`
	BioText           string    `json:"bio_text"`
	Favorites         int32     `json:"favorites"`
	Followers         int32     `json:"followers"`
	Following         int32     `json:"following"`
	Mentions          int32     `json:"mentions"`
	Tweets            int32     `json:"tweets"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}
