// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"context"
)

type Querier interface {
	CreateTweet(ctx context.Context, arg CreateTweetParams) (Tweet, error)
	CreateUser(ctx context.Context, username string) (User, error)
	GetTweet(ctx context.Context, id int64) (Tweet, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListUsersTweets(ctx context.Context, arg ListUsersTweetsParams) ([]Tweet, error)
}

var _ Querier = (*Queries)(nil)
