// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: user.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, hashed_password)
VALUES ($1, $2, $3)
RETURNING id, username, email, hashed_password, profile_picture_url, header_picture_url, bio_text, favorites, followers, following, mentions, tweets, created_at, updated_at
`

type CreateUserParams struct {
	Username       string `json:"username"`
	Email          string `json:"email"`
	HashedPassword string `json:"hashed_password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.Email, arg.HashedPassword)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.HashedPassword,
		&i.ProfilePictureUrl,
		&i.HeaderPictureUrl,
		&i.BioText,
		&i.Favorites,
		&i.Followers,
		&i.Following,
		&i.Mentions,
		&i.Tweets,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, username, email, hashed_password, profile_picture_url, header_picture_url, bio_text, favorites, followers, following, mentions, tweets, created_at, updated_at
FROM users
WHERE username = $1
LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.HashedPassword,
		&i.ProfilePictureUrl,
		&i.HeaderPictureUrl,
		&i.BioText,
		&i.Favorites,
		&i.Followers,
		&i.Following,
		&i.Mentions,
		&i.Tweets,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
